import json

location_types = {
    'Asia': 'continent',
    'Libya': 'country/region',
    'Europe': 'continent',
    'Spain': 'country/region',
    'Lyon': 'city',
    'Africa': 'continent',
    'Persia': 'country/region',
    'Sardis': 'city',
    'Buda': 'city',
    'Greece': 'country/region',
    'Macedonia': 'country/region',
    'Bactria': 'country/region',
    'Alexandria': 'city',
    'Babylon/Babilon': 'city',
    'Aegean': 'natural features',
    'Euphrates': 'natural features',
    'Arabia': 'country/region',
    'Finsbury': 'city',
    'Wales': 'country/region',
    'Hexham': 'city',
    'England': 'country/region',
    'Flanders': 'country/region',
    'Westminster': 'city',
    'Scotland': 'country/region',
    'London': 'city',
    'France/Fraunce': 'country/region',
    'India': 'country/region',
    'Leyre': 'natural features',
    'Brabant': 'country/region',
    'Antwerp/Anwerpe': 'city',
    'Saxony': 'country/region',
    'Trier': 'city',
    'Cornwall/Corn-Wale': 'country/region',
    'Brandenburg': 'country/region',
    'Rhein/Rhine': 'natural features',
    'Germany': 'country/region',
    'Gallia': 'country/region',
    'Holland': 'country/region',
    'Albion': 'country/region',
    'Syria': 'country/region',
    'Carthage': 'city',
    'Ganges': 'natural features',
    'Thessaly/Aeolia': 'country/region',
    'Lerna': 'natural features',
    'Scythia': 'country/region',
    'Nile': 'natural features',
    'Philippi': 'city',
    'Pharsalus/Pharsailaes': 'city',
    'Caspian': 'natural features',
    'Memphis': 'city',
    'Lambeth': 'city',
    'Denmark': 'country/region',
    'Windsor': 'city',
    'Lubeck': 'city',
    'Chester': 'city',
    'Manchester': 'city',
    'Valentia': 'country/region',
    'Paris': 'city',
    'Tiber': 'natural features',
    'Caucasus': 'natural features',
    'Ethiope': 'country/region',
    'Corinth': 'city',
    'Baiae': 'city',
    'Yorkshire': 'country/region',
    'Brittany': 'country/region',
    'Venice': 'city',
    'Croydon': 'city',
    'Kent': 'country/region',
    'Delphos': 'city',
    'Hartford': 'city',
    'Norfolk/Norffolke': 'country/region',
    'Cambridge': 'city',
    'Waltham': 'city',
    'Essex': 'country/region',
    'Stratford': 'city',
    'Edmonton': 'city',
    'Richmond': 'city',
    'Newcastle': 'city',
    'Netherlands/Dutch-Land': 'country/region',
    'Salisbury': 'city',
    'York': 'city',
    'Normandy': 'country/region',
    'Padua': 'city',
    'Cambria/Cambrick': 'country/region',
    'Northampton': 'city',
    'Lichfield': 'city',
    'Britain/BRITANIA': 'country/region',
    'Oxford/Oxenford': 'city',
    'Northumberland/Northumbria': 'country/region',
    'Lancaster': 'city',
    'Cheshire': 'country/region',
    'Nottingham': 'city',
    'Wakefield': 'city',
    'Lancashire': 'country/region',
    'Assyria': 'country/region',
    'Scilly': 'country/region',
    'Brainford': 'city',
    'White-hall': 'city',
    'Putney': 'city',
    'Vienna': 'city',
    'Savona': 'city',
    'Swisserland/Switzerland': 'country/region',
    'Pontremoli': 'city',
    'Mediterranean/Mediterean': 'natural features',
    'Malta': 'country/region',
    'Capua': 'city',
    'Turkey/Turk/Anatolia': 'country/region',
    'Calabria': 'country/region',
    'Italy': 'country/region',
    'Naxos': 'country/region',
    'Naples': 'city',
    'Castalian': 'natural features',
    'Terracina': 'city',
    'Lombardy': 'country/region',
    'Romania': 'country/region',
    'Tuskany': 'country/region',
    'Camerine': 'city',
    'Fleet Street': 'city',
    'Armenia/Hermenia': 'country/region',
    'Iberia': 'country/region',
    'Barcelona': 'city',
    'Madrid': 'city',
    'Bruges': 'city',
    'Cyprus': 'country/region',
    'Arras': 'city',
    'America': 'continent',
    'Rhodes': 'country/region',
    'Thames': 'natural features',
    'Ireland': 'country/region',
    'Varna': 'city',
    'Numedia/Numidia': 'country/region',
    'Aegypt': 'country/region',
    'Cannae': 'city',
    'Nantwich': 'city',
    'Hide-park': 'city',
    'Paphos': 'city',
    'Cheapside': 'city',
    'Helicon': 'natural features',
    'China': 'country/region',
    'Olympus': 'natural features',
    'Ossa': 'natural features',
    'Maidenhead': 'city',
    'Indus': 'natural features',
    'Indies': 'country/region',
    'Caire': 'city',
    'Verona': 'city',
    'Mantua': 'city',
    'Milford': 'city',
    'Holborn': 'city',
    'Dover': 'city',
    'Bow-lane': 'city',
    'Suffolk': 'country/region',
    'Canary': 'country/region',
    'Barbary': 'country/region',
    'Amsterdam': 'city',
    'Norwich': 'city',
    'Tempe': 'natural features',
    'Islington': 'city',
    'Hogsden': 'city',
    'Hungary': 'country/region',
    'Lincolnshire': 'country/region',
    'Middlesex': 'country/region',
    'Poland/Polonia': 'country/region',
    'Sweden': 'country/region',
    'Sicily/Sisily': 'country/region',
    'Lucera': 'city',
    'Palermo': 'city',
    'Languedoc': 'country/region',
    'Burgundy': 'country/region',
    'Covent-Garden': 'city',
    'Hammersmith': 'city',
    'Halifax': 'city',
    'Jordan': 'natural features',
    'Florence': 'city',
    'Ephesus': 'city',
    'Jerusalem/Sion/Syon': 'city',
    'Shrewsbury': 'city',
    'Thebes': 'city',
    'Pelion': 'natural features',
    'Cilicia': 'country/region',
    'Thrace': 'country/region',
    'Belgia': 'country/region',
    'Virginia': 'country/region',
    'Monmouth': 'city',
    'Winchester': 'city',
    'Clermont': 'city',
    'Cambray': 'city',
    'Lebanon': 'country/region',
    'Arden': 'natural features',
    'Savoy': 'country/region',
    'Albania': 'country/region',
    'Heidelberg': 'city',
    'Austria': 'country/region',
    'Belgique': 'country/region',
    'Prussia': 'country/region',
    'Tagus': 'natural features',
    'Polonia': 'country/region',
    'Wittenberg': 'city',
    'Milan': 'city',
    'Wapping': 'city',
    'Tunis': 'city',
    'Arcadia': 'country/region',
    'Nicosia': 'city',
    'Patras': 'city',
    'Golgotha': 'natural features',
    'Genoa': 'city',
    'Russia/Muscovia': 'country/region',
    'Toledo': 'city',
    'Tartary': 'country/region',
    'Westphalia': 'country/region',
    'Norway': 'country/region',
    'Sussex': 'country/region',
    'Carrara': 'city',
    'Turin': 'city',
    'Prague': 'city',
    'Sardinia': 'country/region',
    'Parnassus': 'natural features',
    'Eleusis': 'city',
    'Achaia': 'country/region',
    'Castile': 'country/region',
    'Portugal': 'country/region',
    'Troy/Illium': 'city',
    'Cesarea': 'city',
    'Bethlem': 'city',
    'Bergamo': 'city',
    'Belgrad': 'city',
    'Orleans/Orleance': 'city',
    'Rumford': 'city',
    'Smithfield': 'city',
    'Ludgate': 'city',
    'Pimlico': 'city',
    'Tuscana': 'country/region',
    'West-ham': 'city',
    'Liege': 'city',
    'Cornhill': 'city',
    'Alpine': 'natural features',
    'Canterbury': 'city',
    'Staffordshire': 'country/region',
    'Doncaster': 'city',
    'Sturbridge': 'city',
    'Rochester': 'city',
    'Guilford': 'city',
    'Wight': 'country/region',
    'Emden': 'city',
    'Roterdam': 'city',
    'London-Bridge': 'city',
    'Amiens': 'city',
    'Gades': 'country/region',
    'Gaule': 'country/region',
    'Latium': 'country/region',
    'Frankford': 'city',
    'Lapland': 'country/region',
    'Dinant': 'city',
    'Geneva': 'city',
    'Oeta': 'natural features',
    'Bengala': 'country/region',
    'Luca': 'city',
    'Surrey': 'country/region',
    'Durham': 'city',
    'Bohemia': 'country/region',
    'Taunton': 'city',
    'Yorkish': 'country/region',
    'Ligorne': 'city',
    'Corsica': 'country/region',
    'Syracusa': 'city',
    'Doway': 'city',
    'Tarifa': 'city',
    'Lepanto': 'city',
    'Lincoln': 'city',
    'Grecia': 'country/region',
    'Iudea': 'country/region',
    'Damasco/Damascus': 'city',
    'Laxfield': 'city',
    'Kendal': 'city',
    'Bradford': 'city',
    'Mexico': 'country/region',
    'Magnesia': 'country/region',
    'Bizantium': 'city',
    'Amasia': 'city',
    'Euboea': 'natural features',
    'Smirna': 'city',
    'Edenborough': 'city',
    'Mazara': 'city',
    'Leaden-hall': 'city',
    'Bucklers-Bury': 'city',
    'Avernus': 'natural features',
    'Calidon/Calidonian': 'country/region',
    'Cremona': 'city',
    'Lemnos': 'natural features',
    'Pylos': 'city',
    'Palestine': 'country/region',
    'Plimouth': 'city',
    'Forset': 'country/region',
    'Somersetshire': 'country/region',
    'Lybia': 'country/region',
    'Calecut': 'city',
    'Araby': 'country/region',
    'Troyes': 'city',
    'Tenedos': 'natural features',
    'Ithaca': 'natural features',
    'Aulis': 'natural features',
    'Mycene/Mycoene': 'city',
    'Argo': 'city',
    'Hellespont': 'natural features',
    'Apulia': 'country/region',
    'Mauritania/Mauritans': 'country/region',
    'Colman-street': 'city',
    'Marseilles': 'city',
    'Campania': 'country/region',
    'Pontia': 'city',
    'Broughton': 'city',
    'Salem': 'city',
    'Westchester': 'city',
    'Vicenza': 'city',
    'Westminster-hall': 'city',
    'Newgate': 'city',
    'Bury': 'city',
    'Tilbury': 'city',
    'Niger': 'natural features',
    'Vesuvius': 'natural features',
    'Hymettus': 'natural features',
    'Tigris': 'natural features',
    'Lisbon/Lisborne': 'city',
    'Banbury': 'city',
    'Humber': 'natural features',
    'Lesbos': 'natural features',
    'Pisidia': 'country/region',
    'Phrygia/Phrigia': 'country/region',
    'Etna/Etnean': 'natural features',
    'Israel': 'country/region',
    'Constantinople': 'city',
    'Zanthus': 'city',
    'Lutetia': 'city',
    'Bosphorus': 'natural features',
    'Camden': 'city',
    'Vrbin': 'city',
    'Muscat': 'city',
    'Famagusta': 'city',
    'Colchester': 'city',
    'Hull': 'city',
    'Parma': 'city',
    'Pienza': 'city',
    'Aleppo': 'city',
    'Phlegraean': 'natural features',
    'Pelusium': 'city',
    'Samos': 'natural features',
    'Pharos': 'natural features',
    'Etruria': 'country/region',
    'Galatia': 'country/region',
    'Veii': 'city',
    'Aventine': 'natural features',
    'Zealand': 'country/region',
    'Chyos': 'city',
    'Morocco': 'country/region',
    'Ragusa': 'city',
    'Gibraltar': 'natural features',
    'Rutland': 'country/region',
    'Maidstone': 'city',
    'Bologna': 'city',
    'Severn': 'natural features',
    'Dunmow': 'city',
    'Marchland': 'country/region',
    'Hereford': 'city',
    'Hygate/Hye-gate': 'city',
    'Eltham': 'city',
    'Huntington': 'city',
    'Southhampton': 'city',
    'Acton': 'city',
    'Wrotham': 'city',
    'Carterton': 'city',
    'Carmarthen/Carmarden': 'city',
    'Gloster': 'city',
    'Bristow': 'city',
    'Carnarvon': 'city',
    'Nazareth': 'city',
    'Tanger': 'city',
    'Crete': 'natural features',
    'Abington': 'city',
    'Corcyra': 'natural features',
    'Bishopsgate': 'city',
    'Paddington': 'city',
    'Sandwitch': 'city',
    'Rome/Roma': 'city',
    'Aquitane': 'country/region',
    'Mertia': 'country/region',
    'Cornubia': 'country/region',
    'Albany': 'city',
    'Bedford': 'city',
    'Pelham': 'city',
    'Ruddington': 'city',
    'Leith': 'city',
    'Clifton': 'city',
    'Roan': 'city',
    'Gelderland': 'country/region',
    'Friesland': 'country/region',
    'Hollinghead': 'city',
    'Newmarket': 'city',
    'Tyre': 'city',
    'Yarmouth': 'city',
    'Valtoline': 'country/region',
    'Iapan': 'country/region',
    'Murcia': 'city',
    'Bath': 'city',
    'Placentia': 'city',
    'Calais': 'city',
    'Mesopotamia': 'country/region',
    'Tibet': 'country/region',
    'Mountford': 'natural features',
    'Grimsby': 'city',
    'Ancona': 'city',
    'Delos': 'natural features',
    'Leyden': 'city',
    'Thrasimene': 'natural features',
    'Athens': 'city',
    'Goteham': 'city',
    'Nastricht': 'city',
    'Brunschweige': 'city',
    'Swethia': 'country/region',
    'Portingale': 'country/region',
    'Aragon': 'country/region',
    'Gloster-shyre': 'country/region',
    'Marklane': 'city',
    'Fangringosse': 'city',
    'Porchmouth': 'city',
    'Hircania': 'country/region',
    'Laterans': 'city',
    'Mongibell': 'natural features',
    'Nauarre': 'country/region',
    'Galily': 'country/region',
    'Peadmont': 'country/region',
    'Ramme-alley': 'city',
    'Salimanca': 'city',
    'Andoluzia': 'country/region',
    'Meldauia': 'country/region',
    'Milke-street': 'city',
    'Olympia': 'city',
    'Dunghilford': 'city',
    'Fishstreet': 'city',
    'Saint Antholins, Budge Row': 'city',
    'Totnam': 'city',
    'Somerset': 'country/region',
    'Cythaeron': 'natural features',
    'Luningberg': 'city',
    'Baltick': 'natural features',
    'Pauia': 'city',
    'Siena': 'city',
    'Pisa': 'city',
    'Loth-bury': 'city',
    'Brest': 'city',
    'Graies-Inne': 'city',
    'Watlingstréete': 'city',
    'Towerstréet': 'city',
    'Hartfordshire': 'country/region',
    'Eastcheape': 'city',
    'Morefeilds': 'city',
    'Ausburgh': 'city',
    'Tyburne': 'city',
    'Shoredich': 'city',
    'Sparta/Lacedemon': 'city',
    'Peru': 'country/region',
    'Kingston': 'city',
    'Warwicke': 'city',
    'Cyprisse': 'city',
    'Dansick': 'city',
    'Volga': 'natural features',
    'Fremingham': 'city',
    'Brodgates': 'city',
    'Fresingfield': 'city',
    'Crackfield': 'city',
    'Hampton': 'city',
    'Cuba': 'country/region',
    'Trypoly': 'city',
    'Fanchurch-streete': 'city',
    'Dunkerke': 'city',
    'Lumberstreet': 'city',
    'Colchian': 'country/region',
    'Colchos': 'country/region',
    'Canwicke-streete': 'city',
    'Goulden-lane': 'city',
    'Kentstreet': 'city',
    'Cowslane': 'city',
    'Detford': 'city',
    'Lincolnes-Inne': 'city',
    'Rhodons': 'city',
    'Nemaean': 'natural features',
    'Bosphoron': 'natural features',
    'Pactolus': 'natural features',
    'Muscouia': 'country/region',
    'Saba': 'country/region',
    'Greekish': 'country/region',
    'Pampelonia': 'city',
    'Vtica': 'city',
    'Cycily': 'country/region',
    'Oxfordshiere': 'country/region',
    'Blomsbury': 'city',
    'White-Friers': 'city',
    'Quinborough': 'city',
    'Tyrrhenic/Tyrhen': 'natural features',
    'Barkhamsted': 'city',
    'Vlster': 'country/region',
    'Brickhil-lane': 'city',
    'Hounsditch': 'city',
    'Swauia': 'country/region',
    'Colbrooke': 'city',
    'Barkeshire': 'country/region',
    'Biscany': 'country/region',
    'Transilvania': 'country/region',
    'Grubstreet': 'city',
    'Leystershire': 'country/region',
    'Harcop': 'city',
    'Parthesia': 'country/region'
}


if __name__ == "__main__":
    print("Creating geojson files for each location type...")
    with open("./src/data/database.json", "r") as file:
        data = json.load(file)

    location_types_unique = []
    for location in location_types.values():
        if location not in location_types_unique:
            location_types_unique.append(location)
            
    location_types_unique

    for unique_type in location_types_unique:
        print(f"Processing {unique_type}...")
        geojson = {
            "type": "FeatureCollection",
            "features": []
        }
        for el in data:
            if location_types[el['original_label']] == unique_type:
                feature = {
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [el['coordinates'][1], el['coordinates'][0]]
                    },
                    "properties": {
                        "name": el['location'].replace("'", '`'),
                        "type": unique_type,
                        "titles": el['titles'],
                        "original_label": el['original_label'].replace("'", '`'),
                        "count": len(el['titles']),
                        
                    }
                }
                geojson["features"].append(feature)
        if unique_type == "country/region":
            unique_type = "country_region"
        if unique_type == "natural features":
            unique_type = "naturalfeatures"
        with open(f"./src/data/{unique_type}.geojson", "w") as file:
            file.write(str(geojson).replace("'", '"'))
        print(f"Finished processing {unique_type}...")
    print("Finished creating geojson files.")